swagger: '2.0'
info:
  description: API for Car Operations
  version: "1.0.0"
  title: Car API

# Base path for host
host: 'localhost:8080'
basePath: '/api/car'
schemes:
  - http

# Consumes and Produces types
consumes:
  - application/json
produces:
  - application/json

paths:
  /brands:
    get:
      summary: Get all car brands
      description: Endpoint to get all car brands
      responses:
        200:
          description: A list of car makers
          schema:
            type: array
            items:
              $ref: '#/definitions/CarMaker'

  /models:
    get:
      summary: Get all car models
      description: Endpoint to get all car models
      responses:
        200:
          description: A list of car models
          schema:
            type: array
            items:
              $ref: '#/definitions/CarModel'

  /models/{brandName}:
    get:
      summary: Get car models for a specific brand
      description: Endpoint to get car models for a specific brand
      parameters:
        - name: brandName
          in: path
          required: true
          type: string
          description: The name of the car brand
      responses:
        200:
          description: A list of car models for the specified brand
          schema:
            type: array
            items:
              $ref: '#/definitions/CarModel'
        404:
          description: Brand not found

  /models/{model}:
    get:
      summary: Get car versions by model
      description: Endpoint to get car versions for a specific model
      parameters:
        - name: model
          in: path
          required: true
          type: string
          description: The model of the car
      responses:
        200:
          description: A list of car versions for the specified model
          schema:
            type: array
            items:
              $ref: '#/definitions/CarVersion'
        404:
          description: Model not found

definitions:
  CarMaker:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      country:
        type: string

  CarModel:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      maker:
        $ref: '#/definitions/CarMaker'

  CarVersion:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      model:
        $ref: '#/definitions/CarModel'
